name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install CI tools
      run: make install-tools

    - name: Run linter
      run: make lint

    - name: Run tests
      run: make test

    - name: Build backend linux amd64
      run: make build_backend_linux_amd64

    - name: Build backend windows amd64
      run: make build_backend_windows_amd64